name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main  # change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # or the version compatible with your Jekyll site

      - name: Install Bundler and dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .           # <-- root folder
          destination: ./_site # <-- output folder

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
